name: Build

on:
  push:
    tags:
      - 'v1.*'
  workflow_dispatch:

jobs:
  cancel:
    name: "Cancel previous workflow runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: build.yaml
          access_token: ${{ github.token }}

  build_amd64:
    name: "Build and push container image (AMD64)"
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        env:
          CONTAINER_REGISTRY_PAT: ${{ secrets.CONTAINER_REGISTRY_PAT }}
        run: |
          buildah login -u "${GITHUB_REPOSITORY_OWNER}" -p "${CONTAINER_REGISTRY_PAT}" ghcr.io

      - name: Build and push kubelet container image
        run: |
          make push-amd64

  build_arm64:
    name: "Build and push container image (ARM64)"
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Checkout repository files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        env:
          CONTAINER_REGISTRY_PAT: ${{ secrets.CONTAINER_REGISTRY_PAT }}
        run: |
          buildah login -u "${GITHUB_REPOSITORY_OWNER}" -p "${CONTAINER_REGISTRY_PAT}" ghcr.io

      - name: Build and push kubelet container image
        run: |
          make push-arm64

  manifest:
    name: "Build and push container image manifest"
    runs-on: ubuntu-latest
    needs:
      - build_amd64
      - build_arm64
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        env:
          CONTAINER_REGISTRY_PAT: ${{ secrets.CONTAINER_REGISTRY_PAT }}
        run: |
          buildah login -u "${GITHUB_REPOSITORY_OWNER}" -p "${CONTAINER_REGISTRY_PAT}" ghcr.io

      - name: Build and push container image manifest
        run: |
          make manifest
